### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by mgratzer** [threeMF/threeMF#1]
In exceptional cases the TCP socket reports a "Connection refused error". I'm not able to reproduce it all the time but it seems to occur more often on resuming with automatic reconnections.

**Comment by semireg** [comment]
I can reproduce this.  It seems to happen when a connector with a published command (server) exits and then restarts within a short time interval.  The two instances use different ports (which is fine).  The problem is that the client or underlying system caches the port number of the first instance.  The second (active) port isn't used.

I've traced it back to TMFPeer.m -firstAddress which is called from -portForCommandName:.  The bug itself is deeper inside GCDAsyncSocket's -portFromAddress.  As far as TMFTcpChannel is concerned, the call to -connectToHost:onPort:error: returns no error (it should!).  However, immediately afterwards GCDAsyncSocket calls an error.

Here are the logs:

Trying to connect to Caylans-MacBook-Pro.local.:59714

Connected to Caylans-MacBook-Pro.local.:59714  (this is the cached port)

TCP Socket (<GCDAsyncSocket: 0x1022261d0>) disconnected with Error: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo=0x102388310 {NSLocalizedDescription=Connection refused, NSLocalizedFailureReason=Error in connect() function}

Creating socket for peer Caylans-MacBook-Pro.local. 5FDF57B1-BA0F-4B46-A889-B2F319C8A27B JsonRPC,1.0
2013-06-26 12:42:04.820 MASS Client[90574:120f] Socked <<GCDAsyncSocket: 0x1022261d0>> to Caylans-MacBook-Pro.local. 5FDF57B1-BA0F-4B46-A889-B2F319C8A27B JsonRPC,1.0 disconnected with error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo=0x102388310 {NSLocalizedDescription=Connection refused, NSLocalizedFailureReason=Error in connect() function}.

Somehow the first port needs to be invalidated.  I played around with:

```
- (BOOL)connectWithAddress4:(NSData *)address4 address6:(NSData *)address6 error:(NSError **)errPtr
...
        // Since we're going to be binding to a specific port,
        // we should turn on reuseaddr to allow us to override sockets in time_wait.

        int reuseOn = 1;
        setsockopt(socketFD, SOL_SOCKET, SO_REUSEADDR, &reuseOn, sizeof(reuseOn));
```

That didn't help.  But... I think my guess was close.

See https://github.com/robbiehanson/CocoaAsyncSocket/pull/159 and then https://github.com/dirkx/CocoaAsyncSocket/commit/5ec8c83d59ecb754824f706198eb62e29961c1be.

Thoughts?  Perhaps GCDAsyncSocket framework needs to be a required cocoapod instead of copied into this library directly.

**Comment by semireg** [comment]
I've tested more and feel that this condition happens most often when building in Xcode.  Specifically, pressing CMD-R to "Run" will SIGKILL (kill -9) the current process.  This means that the bonjour service is abandoned and is probably left to timeout on its own.  Therefore, I don't think anyone will have much luck except to handle the error gracefully and retry.
